version: "3"

volumes:
  data:

services:
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  nextjs:
    build: .
    volumes:
      - .:/app
    environment:
      DB_LOCAL_URL: mongodb://database:27017/next-docker
    depends_on:
      - database


  nginx:
    build: ./nginx
    ports:
      - 80:80
